// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92wv57NKBd-kKErwuwWa8Itd7UqR1gpc',
    appId: '1:643407389524:web:825118b35edc33f83b5ec1',
    messagingSenderId: '643407389524',
    projectId: 'contact-app-3f61b',
    authDomain: 'contact-app-3f61b.firebaseapp.com',
    storageBucket: 'contact-app-3f61b.appspot.com',
    measurementId: 'G-9NC3Y07ZGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmXav37LiBxYz45qhxAk2JEHXTvhT8tUo',
    appId: '1:643407389524:android:c4fd4b5c00a0a0f63b5ec1',
    messagingSenderId: '643407389524',
    projectId: 'contact-app-3f61b',
    storageBucket: 'contact-app-3f61b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5sBVMY6um1rMSTxEGtYefM7b0_uEnlIE',
    appId: '1:643407389524:ios:99ce1be3653f50a73b5ec1',
    messagingSenderId: '643407389524',
    projectId: 'contact-app-3f61b',
    storageBucket: 'contact-app-3f61b.appspot.com',
    iosBundleId: 'com.example.contactsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5sBVMY6um1rMSTxEGtYefM7b0_uEnlIE',
    appId: '1:643407389524:ios:f472b4afd8e47cd93b5ec1',
    messagingSenderId: '643407389524',
    projectId: 'contact-app-3f61b',
    storageBucket: 'contact-app-3f61b.appspot.com',
    iosBundleId: 'com.example.contactsApp.RunnerTests',
  );
}
